Fixed Python 3.9+ depreciation error:  Changed "tostring()" to "tobytes()"
Fixed Python 3.9+ depreciation error: 

AttributeError: 'array.array' object has no attribute 'tostring'

array.array: tostring() and fromstring() methods have been removed. They were aliases to tobytes() and frombytes()